export const items = [
  {
    type: "CAR_MP",
    car_data: {
      cargroup_id: 704,
      car_id: -26392,
      name: "Thar 2021",
      brand: "Mahindra",
      location: {
        location_id: 80734,
        lat: 12.90779,
        lng: 77.56093,
        distance: 0.0,
        hd_ids: [],
        terminal_ids: [],
      },
      pricing: {
        id: "20000",
        flexi_name: "FLEX_1000",
        actual_amount: null,
        payable_amount: "₹388/hr",
        revenue: 0,
        state: null,
        offer_id: null,
        discounted_info_text: null,
        fare_header: null,
        fare_breakup: null,
        price_per_hour: 388,
      },
      accessories: ["Manual", "Diesel", "4 Seats"],
      messages: [
        {
          icon: null,
          text: "Available from 13 November",
          icon_url: null,
          category: null,
        },
      ],
      image_urls:
        "https://zoomcar-assets.zoomcar.com/25578/HostCarImage/host_car_image_255783405f7ed-c801-4169-9bff-e8b2d7055ce5.jpg20230109-56-1aqpd27",

      city: {
        search_city_id: 1,
        display_name: "Bangalore",
        link_name: "bangalore",
      },
      rating_v3: {
        rating: "4.59",
        trips: "62 Trips",
        reviews: "28 Reviews",
      },
      tag_run_id: 0,
      car_tags: [
        {
          id: 1,
          colour: "YELLOW_SIX",
          name: "Super Host",
          description: "New cars added to the zoomcar universe",
        },
      ],
      car_ds: {
        tag_run_id: "4854",
      },
      search_params: {
        "seek.car_id": "-26392",
        "seek.city_id": "1",
        "seek.lng_e5": "7756093",
        "seek.location_id": "80734",
        "seek.lat_e5": "1290779",
      },
      is_original_car_images: false,
      highlighted: false,
      response_id: "7AA1E762-2615-4C88-885E-8916373BF09B",
      nth_score: 0.0,
      fulfilment: 0.0,
      jit_fulfilment: 0.0,
      home_weight: 0.0,
      search_weight: 0.0,
      trip_count: 62,
      show_page_control: false,
    },
    car: true,
    banner: false,
  },
  {
    type: "CAR_MP",
    car_data: {
      cargroup_id: 169,
      car_id: 19628,
      name: "Seltos 2020",
      brand: "KIA",
      location: {
        location_id: 108809,
        lat: 12.93951,
        lng: 77.7359,
        distance: 0.0,
        hd_ids: [],
        terminal_ids: [],
      },
      pricing: {
        id: "20000",
        flexi_name: "FLEX_1000",
        actual_amount: null,
        payable_amount: "₹307/hr",
        revenue: 0,
        state: null,
        offer_id: null,
        discounted_info_text: null,
        fare_header: null,
        fare_breakup: null,
        price_per_hour: 307,
      },
      accessories: ["Manual", "Petrol", "5 Seats"],
      messages: [
        {
          icon: null,
          text: "Available from 11 November",
          icon_url: null,
          category: null,
        },
      ],
      image_urls:
        "https://zoomcar-assets.zoomcar.com/297389/HostCarImage/cover0c11ddf5-5adc-4ac5-9e8c-012e5d2ec6b7.jpg",

      city: {
        search_city_id: 1,
        display_name: "Bangalore",
        link_name: "bangalore",
      },
      rating_v3: {
        rating: "4.46",
        trips: "235 Trips",
        reviews: "29 Reviews",
      },
      tag_run_id: 0,
      car_ds: {
        tag_run_id: "4854",
      },
      search_params: {
        "seek.car_id": "19628",
        "seek.city_id": "1",
        "seek.lng_e5": "7773590",
        "seek.location_id": "108809",
        "seek.lat_e5": "1293951",
      },
      is_original_car_images: false,
      highlighted: false,
      response_id: "7AA1E762-2615-4C88-885E-8916373BF09B",
      nth_score: 0.0,
      fulfilment: 0.0,
      jit_fulfilment: 0.0,
      home_weight: 0.0,
      search_weight: 0.0,
      trip_count: 235,
      show_page_control: false,
    },
    car: true,
    banner: false,
  },
];
